version: '1'
services:
  app:
    build:
      context: ../..
      dockerfile: ./api/ruby/Dockerfile
    volumes:
      - .:/usr/src/app/ruby
      - ../../public:/usr/src/app/public
    ports:
      - "9001:9001"
    env_file:
      - ../../docker.env
    environment:
      - PUBLIC_DIR_PATH=/usr/src/app/public
